---

###
### Lints all generic and json files in the whole git repository
###

name: testing
on:
  pull_request:
  push:
    branches:
      - master
    tags:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        target:
          - test

    name: "[ ${{ matrix.target }} ${{ matrix.version}} ]"
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Test
        run: |
          make ${target} VERSION=${version}
        env:
          target: ${{ matrix.target }}
          version: ${{ matrix.version }}
